((python-mode . ((eglot-server-programs . '((python-mode) "~/Software/Python/anaconda3/envs/twaml/bin/pyls"))
                 ;;(py-shell-name . "~/Software/Python/anaconda3/envs/twaml/bin/python")
                 ;;(py-ipython-command . "~/Software/Python/anaconda3/envs/twaml/bin/ipython")
                 (python-shell-interpreter . "~/Software/Python/anaconda3/envs/twaml/bin/python")
                 )))
